#"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# File list.
[manager]

prepend_keymap = [
  # keybinds
  { on = [
    "!",
  ], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },

  # movement
  { on = "<C-k>", run = "arrow -1", desc = "Move cursor up 1 entry" },  # i promise this will make sense
  { on = "<C-j>", run = "arrow 1", desc = "Move cursor down 1 entry" }, # i promise this will make sense

  { on = "<Up>", run = "plugin smart-navigation --sync --args='jump -1 -1'", desc = "Go up" },
  { on = "k", run = "plugin smart-navigation --sync --args='jump -1 -1'", desc = "Go up" },

  { on = "<Down>", run = "plugin smart-navigation --sync --args='jump 1 1'", desc = "Go down" },
  { on = "j", run = "plugin smart-navigation --sync --args='jump 1 1'", desc = "Go down" },

  { on = "<Left>", run = "plugin smart-navigation --sync --args='left'", desc = "Go left" },
  { on = "h", run = "plugin smart-navigation --sync --args='left'", desc = "Go left" },

  { on = "<Right>", run = "plugin smart-navigation --sync --args='right'", desc = "Go right" },
  { on = "l", run = "plugin smart-navigation --sync --args='right'", desc = "Go right" },

  { on = "<S-Up>", run = "plugin smart-navigation --sync --args='jump -5 -50'", desc = "Jump upward" },
  { on = "<S-Down>", run = "plugin smart-navigation --sync --args='jump 5 50'", desc = "Jump downward" },

  { on = "<PageUp>", run = "plugin smart-navigation --sync --args='jump -50% -100'", desc = "Jump up half a page" },
  { on = "<PageDown>", run = "plugin smart-navigation --sync --args='jump 50% 100'", desc = "Jump down half a page" },

  { on = "<Enter>", run = "plugin smart-navigation --sync --args='open'", desc = "Open selected files" },

  # previews
  { on = "K", run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = "J", run = "seek 5", desc = "Seek down 5 units in the preview" },
  { on = "T", run = "plugin --sync hide-preview", desc = "Hide or show the preview" },

  { on = "A", run = "create --dir", desc = "Create a dir" },

  # diff
  { on = "<C-d>", run = "plugin diff", desc = "Diff the selected with the hovered file" },
  # TODO: make it so that <C-D> opens up this diff in neovim with the git delta view
  # and optionally has a terminal view open that shows the deltas w/ the `delta` command

  # compression
  { on = [
    "c",
    "a",
  ], run = "plugin compress", desc = "Archive selected files" },

  # chmod
  { on = [
    "c",
    "m",
  ], run = "plugin chmod", desc = "chmod on selected files" },

  # filtering
  { on = [
    "f",
    "g",
  ], run = "plugin fg", desc = "find file by content (fuzzy match)" },
  { on = [
    "f",
    "G",
  ], run = "plugin fg --args='rg'", desc = "find file by content (ripgrep match)" },
  { on = [
    "f",
    "n",
  ], run = "plugin fg --args='fzf'", desc = "find file by filename" },
  { on = [
    "f",
    "f",
  ], run = "filter --smart", desc = "Filter files" },
  { on = [
    "f",
    "F",
  ], run = "plugin smart-filter", desc = "Smart Filter" },

  { on = [
    "s",
  ], run = "plugin searchjump", desc = "searchjump mode" },
  { on = "S", run = "search fd", desc = "Search files by name using fd" },

  { on = [
    "y",
  ], run = [
    '''shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list' --confirm''',
    "yank",
  ], desc = "yank files and copy to clipboard" },
] # Prepend overrides the default keybindings

# Append does not override the default keybindings and instead act as fallbacks
# it has lower priority than the default keybindings
append_keymap = [
  { on = [
    "e",
  ], run = "open", desc = "Open the selected files" },
  { on = [
    "E",
  ], run = "open --interactive", desc = "Open the selected files interactively" },
  { on = [
    "g",
    "n",
  ], run = "cd ~/.config/nvim/", desc = "Go to the nvim directory" },
  { on = [
    "g",
    "v",
  ], run = "cd ~/Videos/", desc = "Go to the videos directory" },
  { on = [
    "g",
    "p",
  ], run = "cd ~/Pictures/", desc = "Go to the pictures directory" },
  { on = [
    "g",
    "s",
  ], run = "cd ~/Pictures/Screenshots/", desc = "Go to the screenshots directory" },
  { on = [
    "g",
    "D",
  ], run = "cd ~/Documents/", desc = "Go to the documents directory" },
  { on = [
    "g",
    "o",
  ], run = "cd ~/Documents/obsidian-vaults", desc = "Go to the obsidian directory" },
]

# Task manager.
#[tasks]

# Select component. e.g. "open with" for files.
#[select]

# Input component. e.g. create, rename, etc.
[input]

prepend_keymap = [{ on = ["<Esc>"], run = "close", desc = "Cancel input" }]

# Completion component. e.g. "cd" path completion.
[completion]
prepend_keymap = [
  { on = "<C-k>", run = "arrow -1", desc = "Move cursor up" },
  { on = "<C-j>", run = "arrow 1", desc = "Move cursor down" },
]

# Help menu.
#[help]
