[manager]
ratio = [1, 4, 3]   # In eighths: [parent, current, preview]
show_hidden = true
show_symlink = true

[opener]
edit = [{ run = 'nvim "$@"', block = true }]
play = [{ run = 'mpv "$@"', orphan = true, for = "unix" }]
open = [{ run = 'xdg-open "$@"', desc = "Open" }]


[plugin]
prepend_fetchers = [
  { id = "git", name = "*", run = "git" },
  { id = "git", name = "*/", run = "git" },
]

prepend_previewers = [{ name = "*.md", run = "glow" }]
